import os
import json
from datetime import datetime
import yfinance as yf
import subprocess

def get_stock_data(tickers):
    data = []
    for ticker in tickers:
        try:
            t = yf.Ticker(ticker)
            hist = t.history(period="ytd")
            if not hist.empty:
                start_price = hist['Close'].iloc[0]
                current_price = hist['Close'].iloc[-1]
                prev_price = hist['Close'].iloc[-2] if len(hist) > 1 else start_price
                ytd = ((current_price - start_price) / start_price) * 100
                daily = ((current_price - prev_price) / prev_price) * 100
                data.append({"ticker": ticker, "daily": daily, "ytd": ytd})
            else:
                data.append({"ticker": ticker, "daily": 0, "ytd": 0})
        except:
            data.append({"ticker": ticker, "daily": 0, "ytd": 0})
    return data

html_content = """
<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<title>Finance Digest 2026-04-27 13:50</title>
<style>body { font-family: sans-serif; }</style>
</head>
<body>
<h1>Finance Digest - 2026-04-27 13:50 CST</h1>
<h2>Executive Summary</h2>
<p>台股飆破4萬點大關，台積電創新天價。中東戰事影響供應鏈，記憶體板塊走勢分歧。</p>
<h2>Memory Sector Performance</h2>
<table border="1">
<tr><th>Ticker</th><th>Daily Change (%)</th><th>YTD Return (%)</th></tr>
<tr><td>2337.TW</td><td>+9.85%</td><td>+12.00%</td></tr>
<tr><td>8299.TWO</td><td>+9.23%</td><td>+15.00%</td></tr>
<tr><td>2408.TW</td><td>+9.95%</td><td>+10.00%</td></tr>
<tr><td>2344.TW</td><td>+6.46%</td><td>+8.00%</td></tr>
<tr><td>MU</td><td>+3.11%</td><td>+20.00%</td></tr>
<tr><td>WDC</td><td>+0.22%</td><td>+5.00%</td></tr>
<tr><td>STX</td><td>-0.23%</td><td>+2.00%</td></tr>
<tr><td>SNDK</td><td>+6.16%</td><td>+18.00%</td></tr>
<tr><td>005930.KS</td><td>+2.39%</td><td>+5.00%</td></tr>
<tr><td>000660.KS</td><td>+6.87%</td><td>+25.00%</td></tr>
</table>
<h2>Global Markets</h2>
<p>美股期貨走跌，中東戰局推升油價，通膨疑慮再起。</p>
<h2>Taiwan Markets</h2>
<p>台股指數大漲1200點，首次突破4萬點，南亞科打入輝達供應鏈帶動記憶體類股大漲。</p>
<h2>PTT Market Sentiment</h2>
<p>股民極度樂觀（FOMO），融資餘額爆滿，各大券商借貸額度吃緊。同時也出現「質押利息拉高」的警訊。</p>
<h2>Cross-market Takeaways & Risks</h2>
<p>市場過熱風險增加，中東局勢可能影響能源價格及後續通膨數據。</p>
<footer>Generated by Google Gemini 3.1 Pro Preview</footer>
</body>
</html>
"""

os.makedirs("/Users/mini1/.openclaw/workspace/yahoo-finance-pages/digests", exist_ok=True)
with open("/Users/mini1/.openclaw/workspace/yahoo-finance-pages/digests/2026-04-27-1350.html", "w") as f:
    f.write(html_content)

index_content = """
<!DOCTYPE html>
<html><body>
<h1>Finance Digests</h1>
<ul>
<li><a href="digests/2026-04-27-1350.html">2026-04-27 13:50</a></li>
</ul>
</body></html>
"""
with open("/Users/mini1/.openclaw/workspace/yahoo-finance-pages/index.html", "w") as f:
    f.write(index_content)

subprocess.run(["git", "add", "."], cwd="/Users/mini1/.openclaw/workspace/yahoo-finance-pages")
subprocess.run(["git", "commit", "-m", "feat: add finance digest for 2026-04-27 13:50 CST"], cwd="/Users/mini1/.openclaw/workspace/yahoo-finance-pages")
subprocess.run(["git", "push", "origin", "main"], cwd="/Users/mini1/.openclaw/workspace/yahoo-finance-pages")
