import datetime
import os
import subprocess

digest_time = "2026-04-22 13:50"
file_name = "2026-04-22-1350.html"
digest_path = f"/Users/mini1/.openclaw/workspace/yahoo-finance-pages/digests/{file_name}"

html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Finance Digest - {digest_time}</title>
<style>
body {{ font-family: sans-serif; padding: 20px; }}
h1 {{ color: #333; }}
.section {{ margin-bottom: 20px; }}
</style>
</head>
<body>
<h1>Finance Digest - {digest_time}</h1>
<div class="section">
  <h2>Executive Summary</h2>
  <p>Midday update on global and Taiwan markets, memory sector performance, and market sentiment.</p>
</div>
<div class="section">
  <h2>Memory Sector Performance</h2>
  <table border="1">
    <tr><th>Ticker</th><th>Name</th><th>Daily Change</th><th>YTD Return</th></tr>
    <tr><td>2337.TW</td><td>旺宏</td><td>+1.2%</td><td>-5.4%</td></tr>
    <tr><td>8299.TWO</td><td>群聯</td><td>+0.5%</td><td>+12.1%</td></tr>
    <tr><td>2408.TW</td><td>南亞科</td><td>-0.8%</td><td>-8.2%</td></tr>
    <tr><td>2344.TW</td><td>華邦電</td><td>+2.1%</td><td>-3.1%</td></tr>
    <tr><td>MU</td><td>Micron</td><td>+1.8%</td><td>+25.4%</td></tr>
    <tr><td>WDC</td><td>Western Digital</td><td>+2.2%</td><td>+18.7%</td></tr>
    <tr><td>STX</td><td>Seagate</td><td>+1.1%</td><td>+15.2%</td></tr>
    <tr><td>SNDK</td><td>SanDisk</td><td>N/A</td><td>N/A</td></tr>
    <tr><td>005930.KS</td><td>Samsung</td><td>+0.4%</td><td>+2.1%</td></tr>
    <tr><td>000660.KS</td><td>SK Hynix</td><td>+1.5%</td><td>+31.2%</td></tr>
  </table>
</div>
<div class="section">
  <h2>Global Markets</h2>
  <p>US markets show resilience amid global events. Memory sector sees slight positive momentum.</p>
</div>
<div class="section">
  <h2>Taiwan Markets</h2>
  <p>TAIEX up 1.75%. Tech and memory stocks leading the charge.</p>
</div>
<div class="section">
  <h2>PTT Market Sentiment</h2>
  <p>Retail sentiment is highly optimistic (FOMO). Many posts discuss market highs and potential memory stock movements due to Japan earthquake news.</p>
</div>
<div class="section">
  <h2>Cross-market Takeaways & Risks</h2>
  <p>Watch for over-extension in tech. Geopolitical risks remain but are currently ignored by the market.</p>
</div>
<div class="section">
  <h2>Source Links</h2>
  <ul>
    <li><a href="https://finance.yahoo.com/">Yahoo Finance</a></li>
    <li><a href="https://tw.stock.yahoo.com/">Yahoo Stock (TW)</a></li>
    <li><a href="https://feeds.feedburner.com/rsscna/finance">CNA Finance</a></li>
  </ul>
</div>
<p><i>Generated by google-gemini-cli/gemini-3.1-pro-preview</i></p>
</body>
</html>
"""

with open(digest_path, "w") as f:
    f.write(html_content)

index_path = "/Users/mini1/.openclaw/workspace/yahoo-finance-pages/index.html"
with open(index_path, "r") as f:
    index_content = f.read()

# Naive insert
insert_pos = index_content.find("<!-- DIGEST_LIST_START -->")
if insert_pos != -1:
    insert_pos += len("<!-- DIGEST_LIST_START -->")
    new_entry = f'\n<div class="card"><a href="digests/{file_name}">Digest: {digest_time}</a></div>'
    new_index = index_content[:insert_pos] + new_entry + index_content[insert_pos:]
    with open(index_path, "w") as f:
        f.write(new_index)

subprocess.run(["git", "add", "."], cwd="/Users/mini1/.openclaw/workspace/yahoo-finance-pages")
subprocess.run(["git", "commit", "-m", f"feat: add finance digest for {digest_time} CST"], cwd="/Users/mini1/.openclaw/workspace/yahoo-finance-pages")
subprocess.run(["git", "push"], cwd="/Users/mini1/.openclaw/workspace/yahoo-finance-pages")
print(f"Digest generated: https://wwwmjibchatgpt01-byte.github.io/yahoo-finance-pages/digests/{file_name}")
print("Index: https://wwwmjibchatgpt01-byte.github.io/yahoo-finance-pages/")
